<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\WebsiteRedirects;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class WebsiteRedirectsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        WebsiteRedirects::create([
            'old_url'=>'/dlya_poddonov.html',
            'new_url'=>'/category/kleyma_dlya_poddonov'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/po_derevu.html',
            'new_url'=>'/category/kleyma_po_derevu'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'kleyma_udarnie.html',
            'new_url'=>'/category/udarnye_kleyma'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/pechati.html',
            'new_url'=>'/category/surguchnye_pechati'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/surguch.html',
            'new_url'=>'/category/surguch'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/vetnadzor.html',
            'new_url'=>'/category/veterenarnye'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/termoustanovky.html',
            'new_url'=>'/category/nagrevateli_kleym'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/po_kozge.html',
            'new_url'=>'/category/kleyma_po_kozhe'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/klishe.html',
            'new_url'=>'/category/klishe_dlya_tisneniya'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/dlya_burgerov.html',
            'new_url'=>'/category/kleyma_dlya_burgerov'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_ippc2.html',
            'new_url'=>'/product/kleymo_ippc'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_ippc4070.html',
            'new_url'=>'/sub_product/kleymo_ippc40x70'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_ippc5560.html',
            'new_url'=>'/sub_product/kleymo_ippc55x60'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_ippc5580.html',
            'new_url'=>'/sub_product/kleymo_ippc55x80'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_ippc7080.html',
            'new_url'=>'/sub_product/kleymo_ippc70x80'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/EUR.html',
            'new_url'=>'/product/kleymo_eur'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/fitosanitarnoe_data.html',
            'new_url'=>'/product/fitosanitarnoe_data'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_uic.html',
            'new_url'=>'/product/kleymo_uic'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/po_ind_maketu.html',
            'new_url'=>'/product/surguchnye_pechati_po_maketu'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/gotovaya.html',
            'new_url'=>'/product/gotovye_surguchnye_pechati'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/zagotovka.html',
            'new_url'=>'/product/zagotovki_pod_pechat'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/ottisk.html',
            'new_url'=>'/product/surguchnyi_ottisc'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/blocknots.html',
            'new_url'=>'/product/klishe_dlya_bloknotov'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/milo.html',
            'new_url'=>'/product/klishe_dlya_myla'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/airbag.html',
            'new_url'=>'/product/klishe_airbag'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/eticketki.html',
            'new_url'=>'/product/klishe_dlya_etiketok'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/plastick.html',
            'new_url'=>'/product/klishe_dlya_plastika'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/folgoi.html',
            'new_url'=>'/product/klishe_dlya_tisneniya_folgoy'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/vizitcki.html',
            'new_url'=>'/product/klishe_dlya_tisneniya_vizitok'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/kleyma_zavod.html',
            'new_url'=>'/product/kleymo_dlya_zavodov'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/kleyma_svarka.html',
            'new_url'=>'/product/kleymo_dlya_svarscikov'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/udarnoe_remeslo.html',
            'new_url'=>'/product/kleymo_dlya_masterov'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/udarnye_dlya_balonnov.html',
            'new_url'=>'/product/kleymo_dlya_ballonov'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/udarnye_nomernye.html',
            'new_url'=>'/product/kleymo_bukvennoe'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_nk-500.html',
            'new_url'=>'/product/nagrevatel_klishe_nk-500'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_nk-1000.html',
            'new_url'=>'/product/nagrevatel_klishe_nk-1000'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_nagr.html',
            'new_url'=>'/product/nagrevatel_klishe_s_regulyatorom'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/payalnicky.html',
            'new_url'=>'/product/payalnik'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_vetnadzor2540.html',
            'new_url'=>'/product/kleymo_vetnadzor'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_finnoz.html',
            'new_url'=>'/product/veterunarnyj_shtamp_finnoz'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_na_unichtojenie.html',
            'new_url'=>'/product/veterunarnyj_shtamp_na_unichtojenie'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_tuberckulez.html',
            'new_url'=>'/product/veterunarnyj_shtamp_teberkulez'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_ckolbasa.html',
            'new_url'=>'/product/veterunarnyj_shtamp_na_kolbasu'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_util.html',
            'new_url'=>'/product/veterunarnyj_shtamp_util'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_mb.html',
            'new_url'=>'/product/kleymo_dlya_myasa_mb'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_vb.html',
            'new_url'=>'/product/kleymo_dlya_myasa_vb'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_t_kvadrat.html',
            'new_url'=>'/product/kleymo_dlya_myasa_t'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_s.html',
            'new_url'=>'/product/kleymo_dlya_myasa_c'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_e.html',
            'new_url'=>'/product/kleymo_dlya_myasa_e'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/page_mk.html',
            'new_url'=>'/product/kleymo_dlya_myasa_mk'
        ]);
        WebsiteRedirects::create([
            'old_url'=>'/figurnoe.html',
            'new_url'=>'/product/kleymo_dlya_myasa_figurnoe'
        ]);
    }
}
